### ISSUE TITLE
Add a template fund distribution

### ISSUE THREAD

**Issue by sbonfert** [Xiphe/budgetbudget#87] opened 2021-11-10 16:50 UTC
I have many categories, that should receive the same funding each month, e.g., rent, subscriptions, insurance.
It would be great to have some kind of template, that could be applied to a certain month, when I start to budget for this month.
This would allow to quickly and reliably fill out the "boring" (since always the same) part of the budget.

**Comment by Xiphe** [comment] 2021-11-15 09:28
I agree! Closing as duplicate of https://github.com/Xiphe/budgetbudget/issues/86

**Closed as completed by Xiphe** 2021-11-15 09:28 UTC
