### ISSUE TITLE
error messages when opening an existing budget 

### ISSUE THREAD

**Issue by pressqu** [Xiphe/budgetbudget#34] opened 2020-04-20 20:07 UTC
when opening a previously saved budget, following errors are displayed in the terminal. 
```
[start:electron] [56663:0420/220440.268553:ERROR:gles2_cmd_decoder.cc(18903)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[start:electron] [56663:0420/220440.268752:ERROR:gles2_cmd_decoder.cc(18924)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[start:electron] [56663:0420/220440.268849:ERROR:gles2_cmd_decoder.cc(13814)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[start:electron] [56663:0420/220450.025253:ERROR:gles2_cmd_decoder.cc(18953)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
```

**Comment by Xiphe** [comment] 2020-04-20 20:59
Can't reproduce that on my machine. 
Seems to be related to chromium on catalina https://github.com/electron/electron/issues/20944
Since even electron said "there's nothing we can do about it" I'll close this here.

**Closed by Xiphe** 2020-04-20 20:59 UTC
